[build]
builder = "nixpacks"
buildCommand = "python -m pip install -r requirements.txt"

[deploy]
startCommand = "python manage.py migrate && python manage.py collectstatic --noinput && gunicorn hollymellon.wsgi"
restartPolicyType = "ON_FAILURE" 